name: Transform submitted NVDA add-ons to views

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '3 * * * *'  # every hour at minute 3

jobs:

  transformAndPush:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
    - name: Checkout addon data
      uses: actions/checkout@v2
      with:
        repository: nvaccess/addon-store-submission
        path: data
    - name: Checkout views repo
      uses: actions/checkout@v2
      with:
        repository: nvaccess/addonDataViews
        path: views
        ref: data-views
    - name: Checkout transformation repo
      uses: actions/checkout@v2
      with:
        path: transform
    - name: Run transformation and push
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd transform/src
        python -m transform ../../data/addons ../../views/en
        cd ../../views
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "`date`"
        git push
